<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE status [
<!ELEMENT status (developers, todo, changes)>
<!ELEMENT developers (person+)>
<!ELEMENT person EMPTY>
<!ATTLIST person
	name CDATA #REQUIRED
	email CDATA #REQUIRED
	id CDATA #REQUIRED
>
<!ELEMENT todo (actions+)>
<!ELEMENT actions (action+)>
<!ATTLIST actions
	priority (high | medium | low) #REQUIRED
>
<!ELEMENT changes (release+)>
<!ELEMENT release (action+)>
<!ATTLIST release
	version CDATA #REQUIRED
	date CDATA #REQUIRED
>
<!ELEMENT action (#PCDATA | link | br | code | ul)*>
<!ATTLIST action
	context (build | code | docs) #IMPLIED
	assigned-to CDATA #IMPLIED
	dev CDATA #IMPLIED
	type (add | fix | remove | update) #IMPLIED
	fixes-bug CDATA #IMPLIED
	due-to CDATA #IMPLIED
	due-to-email CDATA #IMPLIED
>
<!ELEMENT code (#PCDATA)>
<!ELEMENT br EMPTY>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
	href CDATA #REQUIRED
>
<!ELEMENT ul (li)+>
<!ELEMENT li (#PCDATA | link | br | code | ul)*>
<!ENTITY eacute           "&#x000E9;">
<!ENTITY ouml             "&#x000F6;">
<!ENTITY uuml             "&#x000FC;">
]>

<!-- CVS $Id: status.xml,v 1.1 2004-12-14 21:25:16 winnetou25 Exp $ -->

<status>
	<developers>
		<person name="Mateusz Szczap" email="mati@sz.home.pl" id="mati"/>
		<person name="Marcin Naglik" email="mnaglik@gazeta.pl" id="marcin"/>
	</developers>
	
	<todo>
		<actions priority="high">
			<action>
			</action>
		</actions>
	</todo>

	<changes> <!-- version 1.0 -->
		<release version="@version@" date="@date@">
			<action dev="mati">Updated build.xml</action>
			<action dev="mati">Added status.xml</action>
		</release>
	</changes>

</status>
